### ISSUE TITLE
Doesn't work with legacy decorators code generation in browser

### ISSUE THREAD

**Issue by alexkreidler** [tpluscode/rdfine#92]
I ran into an issue trying to use Rdfine in the browser. I have a version of the `DocumentedResourceMixin`, and directly accessing the data using the clownface pointer, I can access it perfectly fine.

However, when trying to access through the decorator/proxy, I simply get undefined when legacy decorators are enabled.

I've included the two babel configs. I also tried reproducing this in jest by modifying babel configs, but I think I had the config setup wrong (because I was in a monorepo with babel's rootMode upward set).

Here's the code in the jest test: https://github.com/alexkreidler/loqu/blob/91ad691aba1960cc347d0a1eb29cd6e09ef40cea/libs/core/tests/rdfine.spec.ts#L67-L110. It's exactly the same in the browser test, but I replaced `stream` with `readable-stream` and `crypto` with `crypto-browserify`. I suspect if you set up a jest test using the code linked above and the two babel configs below, you should see the same results.

In the photos below, look for the log line with output from `console.log("title called", this.__rdfsLabel)`. Sorry the photos are large, I didn't crop them.

Here's the version using the modern decorators proposal, with the following babel config:
```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-typescript",
    "@babel/preset-react"
  ],
  "plugins": [
    [
      "@babel/plugin-proposal-decorators",
      {
        "decoratorsBeforeExport": false
      }
    ],
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-classes",
    "@babel/proposal-object-rest-spread"
  ],
  "babelrcRoots": [
    "*"
  ]
}
```
![image](https://user-images.githubusercontent.com/11166947/97500674-60f4e780-1946-11eb-9be4-52c599cd645f.png)

Here's the version with the legacy decorators enabled:
```
{
  "presets": ["@babel/preset-env", "@babel/preset-typescript", "@babel/preset-react"],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }],
    "@babel/plugin-transform-classes",
    "@babel/proposal-object-rest-spread"
  ],
  "babelrcRoots": ["*"]
}
```
![image](https://user-images.githubusercontent.com/11166947/97500658-5aff0680-1946-11eb-96e9-ce37d81c5842.png)

**Comment by tpluscode** [comment]
Do you indeed require the use of `legacy: true` flag?

I have so far failed to make it work. The problem is described in issue https://github.com/babel/babel/issues/9773 and the root problem is babel which overwrites the properties defined on prototype. Thus even that the decorators get applied, an instance cannot access them.

In rdfine the decorators assume one of two possibilities:

1. Standard decorators -> using babel (with or without `preset-typescript`)
2. Legacy decorators -> using TypeScript with `tsc`

Unfortunately, it turns out the that the `legacy: true` option is not really compatible with TypeScript. The https://github.com/babel/babel/issues/8864#issuecomment-688535867 outlines some of the differences.

If possible, I would avoid adding more code trying to alleviate those differences

**Comment by tpluscode** [comment]
Did this answer your question @alexkreidler ?

**Comment by alexkreidler** [comment]
Hey, sorry for the wait. Yes it did. Thanks for the detailed explanation!
